return PlaceObj('ModDef', {
	'title', "DroneAssemblerPinPlus",
	'description', "Compatible with Cernan Update (Space Race and Green Planet DLC)\n\nAdds information to the Pin and Pin Rollover for the Drone Assembler showing how many Drones are in the construction queue/available prefabs built.\n\nUpdates to show how many BioRobots are in the construction queue after the breakthrough has been completed.\n\nShould be savegame compatible, you might need to rebuild any previously built Drone Assemblers for the updated Pin Information to take affect. \n\nSpecial Thanks to;\nMaul on the SM Modders Discord for the idea\n\nEnjoy !!",
	'image', "thumbnail.jpg",
	'last_changes', "v1 Initial Release",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*preview*",
	},
	'id', "gmLjKmQ",
	'steam_id', "1831818525",
	'pops_desktop_uuid', "8a7f7359-0ee5-432e-9f3d-30d1a651bccf",
	'pops_any_uuid', "3403bb27-3b26-498b-8411-93a54bc3404d",
	'author', "RustyDios",
	'version_major', 1,
	'version', 13,
	'lua_revision', 233360,
	'saved_with_revision', 245618,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1565540937,
	'screenshot1', "preview.jpg",
	'TagInterface', true,
	'TagOther', true,
})